apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-alb
  annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /argo/
        backend:
          service:
           name: argo-combined-app-public
           port:
             number: 80
